import gambartop from '../asset/umum/keraton 2.png'
import gambardepan from '../asset/umum/gbr_1.png'
import gambar1 from '../asset/umum/kerajaan_gambar_1.png'
import gambar2 from '../asset/umum/kerajaan_gambar_2.png'
import gambar3 from '../asset/umum/kerajaan_gambar_3.png'
import gambar4 from '../asset/umum/kerajaan_gambar_4.png'
import bendera_kerajaan from '../asset/umum/bendera_kerajaan.png'
import lambang_kerajaan from '../asset/umum/lambang_kerajaan.png'

// situs

import gambarsitus_top from '../asset/umum/gambar_top_situs.png'
import gambar1_situs from '../asset/umum/gambar1_situs.png'
import gambar2_situs from '../asset/umum/gambar2_situs.png'
import gambar3_situs from '../asset/umum/gambar3_situs.png'
import gambar4_situs from '../asset/umum/gambar4_situs.png'

// aset

import gambaraset_top from '../asset/umum/aset_top_detail.png'
import gambar1_aset from '../asset/umum/aset1_gbr.png'
import gambar2_aset from '../asset/umum/aset2_gbr.png'
import gambar3_aset from '../asset/umum/aset3_gbr.png'
import gambar4_aset from '../asset/umum/aset4_gbr.png'
import lagu from '../asset/umum/Rick-Roll-Sound-Effect.mp3'
import vidio from "../asset/videotest.mp4"

// acara 
import gambaracara_top from '../asset/umum/acara_header.png';
import gambar1_acara from '../asset/umum/acara_1.png'
import gambar2_acara from '../asset/umum/acara_2.png'
import gambar3_acara from '../asset/umum/acara_3.png'
import gambar4_acara from '../asset/umum/acara_4.png'

// flipcard 
import gambar1_flip from '../asset/umum/kerajaan_1.png';
import gambar2_flip from '../asset/umum/kerajaan_2.png';
import gambar3_flip from '../asset/umum/kerajaan_3.png';

// untuk dokumentasi

import jd from "../asset/profile/jdpp.jpg"


 export const dummyWebsiteRequests = [
  {
      id: 1,
      asal_kerajaan: "Keraton Kasunanan Surakarta",
      link_website: "https://kasunanansurakarta.id",
      tanggal_request: "15-03-2025",
      tanggal_selesai: "20-03-2025",
      status: "Selesai"
  },
  {
      id: 2,
      asal_kerajaan: "Kesultanan Yogyakarta",
      link_website: "https://kesultananyogyakarta.id",
      tanggal_request: "18-03-2025",
      tanggal_selesai: "",
      status: "Diajukan"
  },
  {
      id: 3,
      asal_kerajaan: "Kerajaan Bali",
      link_website: "https://kerajaanbali.id",
      tanggal_request: "10-03-2025",
      tanggal_selesai: "",
      status: "Sedang Diproses"
  },
  {
      id: 4,
      asal_kerajaan: "Kesultanan Ternate",
      link_website: "https://kesultananternate.id",
      tanggal_request: "05-03-2025",
      tanggal_selesai: "12-03-2025",
      status: "Selesai"
  },
  {
      id: 5,
      asal_kerajaan: "Kerajaan Kutai",
      link_website: "https://kerajaankutai.id",
      tanggal_request: "22-02-2025",
      tanggal_selesai: "",
      status: "Diajukan"
  }
];
export const data_barplots = [
  {
    nama_lenkgap: "Test1",
    bulan: "Januari",
    total: 10,
  },
  {
    nama_lenkgap: "Test2",
    bulan: "Februari",
    total: 15,
  }, {
    nama_lenkgap: "Test3",
    bulan: "Maret",
    total: 20,
  }, {
    nama_lenkgap: "Test4",
    bulan: "April",
    total: 25,
  }, {
    nama_lenkgap: "Test5",
    bulan: "Mei",
    total: 60,
  },   {
    nama_lenkgap : "Test6",
    bulan : "Juni",
    total : 35,
  },  {
    nama_lenkgap : "Test7",
    bulan : "Juli",
    total : 50,
  },  {
    nama_lenkgap : "Test8",
    bulan : "Agustus",
    total : 65,
  },  {
    nama_lenkgap : "Test9",
    bulan : "September",
    total : 20,
  },   {
    nama_lenkgap : "Test10",
    bulan : "Oktober",
    total : 55,
  },  {
    nama_lenkgap : "Test11",
    bulan : "November",
    total : 60,
  },  {
    nama_lenkgap : "Test12",
    bulan : "Desember",
    total : 65,
  },
]

export const data_showraja = [
  {
    id: 1,
    nama_lenkgap: "Gusti Raden Mas Suryo Partono",
    tanggal: '28 Juni 1948',
    kota_kelahiran: 'Surakarta, Indonesia',
    wangsa: 'mataram',
    nama_ayah: 'Sri Susuhunan Pakubawana XII',
    nama_ibu: 'KRAy. Pradapaningrum/K.R.Ageng',
    agama: 'islam',
    tahun_awal_jabatan: '2004',
    tahun_akhir_jabatan: '2024',
  },
  {
    id: 2,
    nama_lenkgap: "Gusti Raden Mas Suryo Partono",
    tanggal: '28 Juni 1948',
    kota_kelahiran: 'Surakarta, Indonesia',
    wangsa: 'mataram',
    nama_ayah: 'Sri Susuhunan Pakubawana XII',
    nama_ibu: 'KRAy. Pradapaningrum/K.R.Ageng',
    agama: 'islam',
    tahun_awal_jabatan: '2000',
    tahun_akhir_jabatan: 'Sekarang',
  },
]


export const data_flipcard2 = [
  {
    id: 1,
    gambar: gambar1_flip,
    kerajaan: "Keraton Surakarta Kasunanan",
    lokasi: "Surakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },

  {
    id: 2,
    gambar: gambar2_flip,
    kerajaan: "Kesultanan Ngayogyakarta Hadiningrat",
    lokasi: "Yogyakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",

  },
  {
    id: 3,
    gambar: gambar3_flip,
    kerajaan: "Kesultanan Cirebon",
    lokasi: "Cirebon, Jawa Barat",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },
]


export const data_flipcard = [
  {
    id: 1,
    gambar: gambar1_flip,
    kerajaan: "Keraton Surakarta Kasunanan",
    lokasi: "Surakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },

  {
    id: 2,
    gambar: gambar2_flip,
    kerajaan: "Kesultanan Ngayogyakarta Hadiningrat",
    lokasi: "Yogyakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",

  },
  {
    id: 3,
    gambar: gambar3_flip,
    kerajaan: "Kesultanan Cirebon",
    lokasi: "Cirebon, Jawa Barat",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },
  {
    id: 4,
    gambar: gambar1_flip,
    kerajaan: "Keraton Surakarta Kasunanan 2",
    lokasi: "Surakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },

  {
    id: 5,
    gambar: gambar2_flip,
    kerajaan: "Kesultanan Ngayogyakarta Hadiningrat 2",
    lokasi: "Yogyakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",

  },
  {
    id: 6,
    gambar: gambar3_flip,
    kerajaan: "Kesultanan Cirebon 2",
    lokasi: "Cirebon, Jawa Barat",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },
  {
    id: 7,
    gambar: gambar1_flip,
    kerajaan: "Keraton Surakarta Kasunanan 3",
    lokasi: "Surakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  },

  {
    id: 8,
    gambar: gambar2_flip,
    kerajaan: "Kesultanan Ngayogyakarta Hadiningrat 3",
    lokasi: "Yogyakarta, Jawa Tengah",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",

  },
  {
    id: 9,
    gambar: gambar3_flip,
    kerajaan: "Kesultanan Cirebon 3",
    lokasi: "Cirebon, Jawa Barat",
    isi: "Kerajaan-kerajaan yang berdiri di Indonesia berjumlah ratusan. Majelis Agung Raja Sultan Indonesia (MARSI) sendiri merupakan sebuah organisasi yang beranggotakan para Raja beserta dengan Kerajaannya. Anggota MARSI tersebar dari sabang hingga merauke. Melalui laman ini, anda dapat memperkaya pengetahuan anda mengenai ratusan kerajaan yang berdiri di Indonesia.",
  }
]

// detail acara + daftar acara
export const detail_acara = [
  {
    id: 1,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1012,
    daerah: 'Surabaya',
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 2,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1210,
    daerah: 'Surakarta',
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 3,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    daerah: 'Surakarta',
    tahun: 1200,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 4,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    daerah: 'Surakarta',
    tahun: 1122,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 5,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    daerah: 'Surakarta',
    tahun: 1010,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 6,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    daerah: 'Surakarta',
    tahun: 1250,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 7,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    daerah: 'Surabaya',
    tahun: 1019,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 8,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surabaya',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1230,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 9,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surabaya',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1210,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 10,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surabaya',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1012,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 11,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surabaya',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1210,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 12,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surakarta',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1260,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 13,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surakarta',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1276,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 14,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surakarta',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1246,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 15,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surabaya',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1265,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },
  {
    id: 16,
    gambartop: gambaracara_top,
    nama_tempat: "Kirab Malam 1 Suro",
    daerah: 'Surakarta',
    gambar1: gambar1_acara,
    gambar2: gambar2_acara,
    gambar3: gambar3_acara,
    gambar4: gambar4_acara,
    tahun: 1255,
    kepemilikan: "Keraton Kasunanan Surakarta",
    jam_selesai: '23:59 - selesai',
    tanggal_acara: '07/07/2024',
    isi: "Kirab Pusaka Malam 1 Suro  di Keraton Surakarta adalah perayaan tahunan yang menandai tahun baru Jawa dengan pengusungan pusaka keraton. Acara dimulai dengan doa bersama di keraton, diikuti oleh prosesi mengarak pusaka seperti keris dan barang bersejarah, disertai iringan musik gamelan dan tarian tradisional. Masyarakat antusias menyaksikan prosesi yang melambangkan warisan budaya dan spiritualitas. Acara diakhiri dengan ritual penutup untuk menjaga hubungan antara keraton dan rakyat, sekaligus melestarikan tradisi luhur budaya Jawa.",
    lokasi: "Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta, Jawa Tengah"
  },

]

// daftar situs + detail situs 
export const detil_situs = [
  {
    id: 1,
    gambartop: gambaraset_top,
    nama_tempat: "Keraton kasunana surakarta",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 800,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 2,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 820,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 3,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 840,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 4,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 860,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 5,
    gambartop: gambaraset_top,
    nama_tempat: "Keraton kasunana surakarta 2",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 880,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 6,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 2",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 900,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 7,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 2",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1230,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 8,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 3",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1800,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 9,
    gambartop: gambaraset_top,
    nama_tempat: "Keraton kasunana surakarta 3",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1200,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 10,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 4",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1500,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 11,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 5",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1220,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 12,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur 6",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1290,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 13,
    gambartop: gambaraset_top,
    nama_tempat: "Keraton kasunana surakarta A ",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1920,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 14,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur B",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1890,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 15,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur C",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1880,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
  {
    id: 16,
    gambartop: gambarsitus_top,
    nama_tempat: "Candi Borobudur D",
    gambar1: gambar1_situs,
    gambar2: gambar2_situs,
    gambar3: gambar3_situs,
    gambar4: gambar4_situs,
    nomor_cagarbudaya: "CB00123",
    kepemilikan: "Pemerintah Indonesia",
    pendiri: "Dinasti Syailendra",
    tahun: 1750,
    jenis_situs: "Candi Buddha",
    isi: "Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.",
    lokasi: "Magelang, Jawa Tengah, Indonesia"
  },
]

// daftar aset + detail aset
export const tempasetdata = [
  {
    id: 1,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 800,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 2,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 900,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },
  {
    id: 3,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1000,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 4,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1900,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },
  {
    id: 5,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1800,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 6,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1990,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 7,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1880,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 8,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1930,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 9,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1960,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 10,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1980,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 11,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 2000,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 12,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 900,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 13,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1700,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 14,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1400,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 15,
    nama: "Gamelan Sekaten",
    lagu: "",
    aset: "Alat Musik",
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    vidio: vidio,
    tahun: 1870,
    lokasi: 'Surabaya',
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },

  {
    id: 16,
    nama: "Gamelan Sekaten (Contoh Ada Lagu)",
    lagu: lagu,
    vidio: "",
    aset: "Alat Musik",
    tahun: 1920,
    lokasi: 'Surakarta',
    gambartop: gambaraset_top,
    kepemilikan: "Keraton Kasunanan Surakarta",
    isi: "Gamelan sekaten adalah jenis gamelan Jawa yang hanya dimainkan dalam pergelaran upacara adat Sekaten yang diselenggarakan di dua keraton pecahan Kesultanan Mataram, yaitu Kesultanan Ngayogyakarta dan Kesunanan Surakarta Hadiningrat. Upacara adat tersebut diadakan untuk memperingati Maulid Nabi Islam Muhammad. Pertama kali dikembangkan pada zaman Kesultanan Demak, gamelan tersebut dijadikan sebagai media dakwah yang digagas oleh Wali Sanga agar orang Jawa bersedia menganut agama Islam.",
    gambar1: gambar1_aset,
    gambar2: gambar2_aset,
    gambar3: gambar3_aset,
    gambar4: gambar4_aset,
  },
]

// daftar kerajaan + detail kerajaan 
export const tempdata = [
  {
    id: 1,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta',
    tahun: '1800',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    vidio: vidio,
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambardepan: gambardepan,
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
    nama_lenkgap: "Gusti Raden Mas Suryo Partono",
    tanggal: '28 Juni 1948',
    kota_kelahiran: 'Surakarta, Indonesia',
    wangsa: 'mataram',
    nama_ayah: 'Sri Susuhunan Pakubawana XII',
    nama_ibu: 'KRAy. Pradapaningrum/K.R.Ageng',
    agama: 'islam',
    tahun_awal_jabatan: '2004',
    tahun_akhir_jabatan: '2024',
  },
  {
    id: 2,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 2',
    tahun: '1745',
    vidio: vidio,
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    gambardepan: gambardepan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Kota Surakarta, Jawa Tengah',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,

  },
  {
    id: 3,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 3',
    tahun: '1742',
    bendera: bendera_kerajaan,
    gambardepan: gambardepan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Jogjakarta',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 4,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 4',
    tahun: '1798',
    gambardepan: gambardepan,
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Kota Surakarta, Jawa Tengah',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 5,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 5',
    tahun: '1783',
    gambardepan: gambardepan,
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 6,
    gambartop: gambartop,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 6',
    tahun: '1725',
    gambardepan: gambardepan,
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Yogyakarta',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 7,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 7',
    tahun: '1645',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Kota Surakarta, Jawa Tengah',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 8,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 8',
    tahun: '1545',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Yogyakarta',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 9,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Keraton Kasunanan Surakarta 9',
    tahun: '1445',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 10,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Dinasti A',
    tahun: '1655',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Kota Surakarta, Jawa Tengah',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 11,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Keratuan A',
    tahun: '1775',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Yogyakarta',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 12,
    gambartop: gambartop,
    gambardepan: gambardepan,

    nama_kerajaan: 'Keprabuan A',
    tahun: '1665',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 13,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Kesultanan A',
    tahun: '1805',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 14,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Kekaisaran A',
    tahun: '1045',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 15,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Kadipaten Mangkunagaran',
    tahun: '1245',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Yogyakarta',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
  {
    id: 16,
    gambartop: gambartop,
    gambardepan: gambardepan,
    nama_kerajaan: 'Kerajaan A',
    tahun: '1325',
    bendera: bendera_kerajaan,
    lambang_kerajaan: lambang_kerajaan,
    alamat: 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon',
    lokasi: 'Surabaya',
    nama_kasunanan: 'Kesunanan Surakarta Hadiningrat (ꦟꦒꦫꦶꦑꦱꦸꦤꦤꦤ꧀ꦯꦸꦫꦏꦂꦠꦲꦢꦶꦤꦶꦁꦫꦠ꧀)',
    isi_singkat: 'Nagari Kasunanan Surakarta Hadiningrat adalah sebuah kerajaan di Pulau Jawa bagian tengah yang berdiri pada tahun 1745, yang merupakan penerus dari Kesultanan Mataram yang beribu kota di Kartasura dan selanjutnya berpindah di Surakarta. Pada tahun 1755, sebagai hasil dari Perjanjian Giyanti yang disahkan pada tanggal 13 Februari 1755 antara VOC (Vereenigde Oostindische Compagnie) dengan Pangeran Mangkubumi, disepakati bahwa wilayah Mataram dibagi menjadi dua pemerintahan, yaitu Surakarta dan Yogyakarta.',
    gambar1: gambar1,
    gambar2: gambar2,
    gambar3: gambar3,
    gambar4: gambar4,
  },
]


export const dummydata = [
  {
    id: 0,
    nama: 'Raja Arthur',
    telepon: '081234567890',
    email: 'arthur@camelot.com',
    kerajaan: 'Camelot',
    jenis_kerajaan: 'Monarki',
    gelar: 'Pendekar Meja Bundar',

  },
  {
    id: 1,
    nama: 'Sultan Saladin',
    telepon: '082345678901',
    email: 'saladin@ayyubid.com',
    kerajaan: 'Ayyubid',
    jenis_kerajaan: 'Kesultanan',
    gelar: 'Sultan Mesir dan Suriah',

  },
  {
    id: 2,
    nama: 'Julius Caesar',
    telepon: '083456789012',
    email: 'caesar@romawi.com',
    kerajaan: 'Romawi',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Konsul & Diktator',

  },
  {
    id: 3,
    nama: 'Genghis Khan',
    telepon: '084567890123',
    email: 'genghis@mongol.com',
    kerajaan: 'Mongol',
    jenis_kerajaan: 'Kekhanan',
    gelar: 'Khan Agung',

  },
  {
    id: 4,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901231',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 5,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901232',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 6,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901233',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 7,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901235',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 8,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901235',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 9,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901236',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 10,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901237',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 11,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901238',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 12,
    nama: 'Napoleon Bonaparte',
    telepon: '085678901239',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 13,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123110',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 14,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123111',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 15,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123112',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 16,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123113',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 17,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123114',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 18,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123115',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 19,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123116',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 20,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123117',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 21,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123118',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 22,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123119',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 23,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123120',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 24,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123121',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
  {
    id: 25,
    nama: 'Napoleon Bonaparte',
    telepon: '08567890123122',
    email: 'napoleon@prancis.com',
    kerajaan: 'Prancis',
    jenis_kerajaan: 'Kekaisaran',
    gelar: 'Kaisar Prancis',

  },
];
export const dummyAcara = [
  {
    id: 0,
    id_acara: "id-1",
    nama_acara: "Ulang Tahun Raden Sukngkono",
    tanggal: "20-03-2025",
    lokasi: "Candi Prambanan, Indonesia",
    penanggungjawab: 'Grace',
    jenis_acara: "Pesta",
    kapasitas: "10000",
    status: "Selesai"
  },
  {
    id: 1,
    id_acara: "id-2",
    nama_acara: "Festival Budaya Nusantara",
    tanggal: "05-06-2025",
    lokasi: "Taman Mini Indonesia Indah, Jakarta",
    penanggungjawab: 'Cienne',
    jenis_acara: "Festival",
    kapasitas: "5000",
    status: "Pending"
  },
  {
    id: 2,
    id_acara: "id-3",
    nama_acara: "Seminar Sejarah Kerajaan",
    tanggal: "12-07-2025",
    lokasi: "Universitas Gadjah Mada, Yogyakarta",
    penanggungjawab: 'Gracienne',
    jenis_acara: "Seminar",
    kapasitas: "300",
    status: "Disetujui"
  },
  {
    id: 3,
    id_acara: "id-4",
    nama_acara: "Pentas Seni Wayang Kulit",
    tanggal: "25-09-2025",
    lokasi: "Pendopo Agung, Surakarta",
    penanggungjawab: 'Adam',
    jenis_acara: "Pertunjukan",
    kapasitas: "1500",
    status: "Ditolak"
  },
  {
    id: 4,
    id_acara: "id-5",
    nama_acara: "Upacara Adat Kasunanan",
    tanggal: "10-11-2025",
    lokasi: "Keraton Surakarta, Jawa Tengah",
    penanggungjawab: 'Hawa',
    jenis_acara: "Upacara Adat",
    kapasitas: "2000",
    status: "Selesai"
  },
  {
    id: 5,
    id_acara: "id-6",
    nama_acara: "Rapat Besar Dewan Adat",
    tanggal: "15-08-2025",
    lokasi: "Gedung Dewan Adat, Jakarta",
    penanggungjawab: 'Yoel',
    jenis_acara: "Rapat",
    kapasitas: "100",
    status: "Berlangsung"
  },
  {
    id: 6,
    id_acara: "id-7",
    nama_acara: "Lomba Masakan Tradisional",
    tanggal: "22-09-2025",
    lokasi: "Lapangan Alun-Alun, Bandung",
    penanggungjawab: 'Gabriel',
    jenis_acara: "Kompetisi",
    kapasitas: "300",
    status: "Pending"
  },
  {
    id: 7,
    id_acara: "id-8",
    nama_acara: "Pameran Artefak Kuno",
    tanggal: "30-10-2025",
    lokasi: "Museum Nasional, Jakarta",
    penanggungjawab: 'Michael',
    jenis_acara: "Pameran",
    kapasitas: "800",
    status: "Disetujui"
  },
  {
    id: 8,
    id_acara: "id-9",
    nama_acara: "Dialog Budaya dan Sejarah",
    tanggal: "15-12-2025",
    lokasi: "Balai Kota, Yogyakarta",
    penanggungjawab: 'Angelo',
    jenis_acara: "Diskusi",
    kapasitas: "250",
    status: "Ditolak"
  },
  {
    id: 9,
    id_acara: "id-10",
    nama_acara: "Festival Reog Ponorogo",
    tanggal: "05-01-2026",
    lokasi: "Alun-Alun Ponorogo, Jawa Timur",
    penanggungjawab: 'Manghamili',
    jenis_acara: "Festival",
    kapasitas: "5000",
    status: "Selesai"
  }
]

// untuk dummy dokumen
export const dummyDocs = [
  {
    id: 0,
    id_dokumen: "DA-01",
    nama_dokumen: "Surat hak Milik Tanah",
    asal_kerajaan: "Kerajaan Jogja",
    jenis_dokumen: "Akte",
    kategori: "terima",
    dokumentasi: "foto",
  },
  {
    id: 1,
    id_dokumen: "DA-02",
    nama_dokumen: "Akta Kelahiran",
    asal_kerajaan: "Kerajaan Solo",
    jenis_dokumen: "Akta",
    kategori: "terima",
    dokumentasi: "salinan",
  },
  {
    id: 2,
    id_dokumen: "DA-03",
    nama_dokumen: "Surat Nikah",
    asal_kerajaan: "Kerajaan Bali",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "foto",
  },
  {
    id: 3,
    id_dokumen: "DA-04",
    nama_dokumen: "Surat Wasiat",
    asal_kerajaan: "Kerajaan Makassar",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "salinan",
  },
  {
    id: 4,
    id_dokumen: "DA-05",
    nama_dokumen: "Surat Keterangan Tanah",
    asal_kerajaan: "Kerajaan Aceh",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "foto",
  },
  {
    id: 5,
    id_dokumen: "DA-06",
    nama_dokumen: "Surat Perjanjian Kerja",
    asal_kerajaan: "Kerajaan Palembang",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "salinan",
  },
  {
    id: 6,
    id_dokumen: "DA-07",
    nama_dokumen: "Akta Pendirian Perusahaan",
    asal_kerajaan: "Kerajaan Madura",
    jenis_dokumen: "Akta",
    kategori: "terima",
    dokumentasi: "foto",
  },
  {
    id: 7,
    id_dokumen: "DA-08",
    nama_dokumen: "Surat Kuasa",
    asal_kerajaan: "Kerajaan Minangkabau",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "salinan",
  },
  {
    id: 8,
    id_dokumen: "DA-09",
    nama_dokumen: "Surat Keterangan Domisili",
    asal_kerajaan: "Kerajaan Batak",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "foto",
  },
  {
    id: 9,
    id_dokumen: "DA-10",
    nama_dokumen: "Surat Keterangan Kematian",
    asal_kerajaan: "Kerajaan Cirebon",
    jenis_dokumen: "Surat",
    kategori: "terima",
    dokumentasi: "salinan",
  }
];
export const dummyGelar = [
  {
    id_gelar: "G-001",
    gelar: "Raja",
  },
  {
    id_gelar: "G-002",
    gelar: "Sultan",
  },
  {
    id_gelar: "G-003",
    gelar: "Pangeran",
  },
];

export const dummyJenisKerajaan = [
  {
    id_jenis: "JK-001",
    jenis: "Kesultanan",
  },
  {
    id_jenis: "JK-002",
    jenis: "Kerajaan Hindu",
  },
  {
    id_jenis: "JK-003",
    jenis: "Kerajaan Buddha",
  },
];

export const dummyDokumen = [
  {
    id_dokumen: "D-001",
    nama: "Prasasti Mulawarman",
  },
  {
    id_dokumen: "D-002",
    nama: "Kitab Negarakertagama",
  },
  {
    id_dokumen: "D-003",
    nama: "Undang-Undang Kerajaan",
  },
];

export const dummyRoleAdmin = [
  {
    id_role: "RA-001",
    role: "Super Admin",
  },
  {
    id_role: "RA-002",
    role: "Editor",
  },
  {
    id_role: "RA-003",
    role: "Viewer",
  },
];
export const dummyKerajaan = [
  {
    id_kerajaan: "KR-100B",
    nama: "Kerajaan Sultan Agung",
    era: "Kolonial",
    lokasi: "Surabaya, Jalan Raya Rungkut Kidul no 35",
    tanggal_berdiri: "20-02-1745",
    jenis: "Kasunanan",
    nama_raja: "Sri Susuhunan Pakubuwana XIII",
    dokumentasi: [jd, jd, jd, jd, jd,]
  }
]